export const GET_WEEKLY_REPORT = '/report/weekly'
export const GET_USER = '/user'
export const GET_BRANCHES = '/branch/'
export const GET_TEMP_USER = '/temporary/user'
export const GET_PRODUCTS = '/product/'
export const LOGOUT_USER = '/auth/logout'
export const GET_STOCK = '/stock'
export const GET_DASHBOARD_MONTHLY_STOCK = '/dashboard/monthly-stock'
export const GET_DASHBOARD_DAILY_SALES = '/dashboard/daily-sales'
export const GET_DASHBOARD_MONTHLY_REPORT = '/report/monthly'
export const GET_DAILY_REPORT = '/report/daily'
export const SEND_EMAIL = '/auth/sendmail'
export const GET_DAILY_REPORT_PDF = '/pdfGenerator/daily'
export const GET_WEEKLY_REPORT_PDF = '/pdfGenerator/weekly'
export const GET_MONTHLY_REPORT_PDF = '/pdfGenerator/monthly'


export const SAVE_DAILY_STOCK = '/stock/'
export const SAVE_USER = '/user/'
export const EDIT_USER = '/user/'
export const AUTH_USER = '/auth/login'
export const AUTH_RESET_PASSWORD = '/auth/pwd-reset'
export const SAVE_PRODUCT = '/product/'
export const EDIT_PRODUCT = '/product/'
export const SAVE_LOCATION = '/branch/'
export const CHANGE_PASSWORD = '/auth/change-password'